language: c

addons:
    apt:
        packages:
            - libxcb1-dev
            - libxcb-icccm4-dev
            - libxcb-randr0-dev
            - libxcb-util0-dev
            - meson
    coverity_scan:
        project:
            name: timber
            description: Tree-based window manager
        notification_email: timber@pks.im
        build_command_prepend: mkdir -p build-coverity && meson . build-coverity
        build_command: ninja -C build-coverity
        branch_pattern: coverity

matrix:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
          if: branch != coverity

env:
    - CFLAGS="-Werror -Wno-padded"

script:
    - mkdir -p build
    - meson --warnlevel=3 . build
    - ninja -C build

branches:
    only:
        - master
        - coverity
